version: '3.7'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: vendure
      POSTGRES_PASSWORD: vendure
      POSTGRES_DB: vendure
    ports:
      - '5432:5432'
  vendure:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_USER: vendure
      DB_PASS: vendure
      DB_NAME: vendure
      SESSION_SECRET: supersecret
    depends_on:
      - postgres
